spring.application.name=flow-manager

spring.datasource.url=jdbc:postgresql://localhost:5433/flowmanager
spring.datasource.username=flowmanager_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.source-bucket=source-files